routes/web.php
<?php

use App\Http\Controllers\ArtistController;
use App\Http\Controllers\CinemaController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\SessionController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", [CinemaController::class, 'index'])->name('home');

Route::get('dashboard', function () {
    return view('dashboard' . "UserController@profile");
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::get("profile", "UserController@profile")->middleware("auth");


Route::prefix('movie')->group(function () {
    //Route::get("/", ['as' => 'movie', 'uses' => 'MovieController@movie']);
    Route::get('{movie}/actors', [MovieController::class, 'actors'])->name('movie.actors');
    Route::post('{movie}/actors', [MovieController::class, 'attach'])->name('movie.attach');
    Route::get('{movie}/actors/{actor}', [MovieController::class, 'detach'])->name('movie.detach');
});


Route::prefix('artist')->group(function () {
    Route::get('{artist}/filmography', [ArtistController::class, 'hasPlayed'])->name('artist.filmography');
    //    Route::get('{artist}/directed', [ArtistController::class, 'hasDirected'])->name('artist.filmography');
});


Route::resource("artist", ArtistController::class);
Route::resource("country", CountryController::class);
Route::resource("movie", MovieController::class);
Route::resource("cinema", CinemaController::class);
Route::resource("room", RoomController::class);
Route::resource("session", SessionController::class);

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/movies/actors.blade.php
<x-app-layout>
    <x-slot name="title">
        Actors for :
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <div class="flex flex-wrap justify-center">
        <div class=" text-center">
            <h1 class="text-5xl font-normal leading-normal mt-0 mb-2 text-stone-100">{{$movie->title}}
            </h1>
            <img src="{{asset('storage/uploads/posters/'.$movie->poster)}}"
                 alt="{{$movie->title}}" width="400px" height="400px" class="mb-5">
        </div>
    </div>

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">

        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">{{__("Profiles")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Actors Name")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Role")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Birthdate")}}</th>

                <th scope="col" class="px-6 py-3">{{__("Actions")}}</th>

            </tr>
            </thead>
            <tbody>
            @foreach($actors as $actor)

                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <td class="px-6 py-4"><img class="rounded-full"
                                               src="{{asset('storage/uploads/profiles/'.$actor->image)}}"
                                               alt="{{$actor->firstname. " ". $actor->name}}" width="100px"
                                               height="150px"></td>
                    <td class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">{{$actor->firstname. " ". $actor->name}}</td>
                    <td class="px-6 py-4">{{$actor->pivot->role}}</td>
                    <td class="px-6 py-4">{{$actor->birthdate}}</td>

                    <td class="px-6 py-4 text-right">
                        <a href="{{route('movie.detach', ["movie"=>$movie->id, "actor"=>$actor->id])}}"
                           class="font-medium text-blue-600 dark:text-blue-500 hover:underline">{{__('Detach')}}</a>
                </tr>
            @endforeach
            </tbody>
        </table>
        <form method="POST" action="{{route('movie.attach', $movie->id)}}" enctype="multipart/form-data">
            {{ csrf_field() }}
            <p>
                <label class="text-gray-100" for="role">Role</label>
                <input type="text" name="role" id="role" value="" required
                       class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
            </p>
            <p>
                <label class="text-gray-100" for="artist_id">Actors</label>
                <select name="artist_id" id="artist_id" required
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                    @foreach($artists as $artist)
                        <option
                            value="{{$artist->id}}"{{$artist->id == $movie->artist_id ? 'selected="selected"' : ''}}>
                            {{$artist->name}}
                            {{$artist->firstname}}
                        </option>
                    @endforeach
                </select>
            </p>
            <button type="submit"
                    class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Attach
            </button>
        </form>

        @if ($errors->any())
            <div>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif


        @if (session("ok"))
            <div>
                {{session("ok")}}
            </div>

        @endif
    </div>

</x-app-layout>

resources/views/movies/create.blade.php
<x-app-layout>
    <x-slot name="title">
        Create Movie
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <form method="POST" action="{{route('movie.store')}}" enctype="multipart/form-data">
        {{ csrf_field() }}

        <p>
            <label class="text-gray-100" for="title">Title</label>
            <input type="text" name="title" id="title" value="" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="year">Year</label>
            <input type="number" name="year" id="year" value="" max="2022" min="1900" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="length">Length</label>
            <input type="number" name="length" id="length" value="" max="500" min="20" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="director_id">Director</label>
            <select name="director_id" id="director_id" required
                    class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                @foreach($artists as $artist)
                    <option value="{{$artist->id}}"{{$artist->id == $movie->artist_id ? 'selected="selected"' : ''}}>
                        {{$artist->name}}
                        {{$artist->firstname}}
                    </option>
                @endforeach
            </select>
        </p>
        <p>
            <label class="text-gray-100" for="country_id">Country</label>
            <select name="country_id" id="country_id" required
                    class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                @foreach($countries as $country)
                    <option value="{{$country->id}}"{{$country->id == $movie->country_id ? 'selected="selected"' : ''}}>
                        {{$country->name}}
                    </option>
                @endforeach
            </select>
        </p>
        <p>
            <label for="poster" class="form-label inline-block mb-2 text-gray-100">Select a poster</label>
            <input type="file" id="poster" name="poster"
                   class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none">
        </p>


        <button type="submit"
                class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Create
        </button>
    </form>

    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    @if (session("ok"))
        <div>
            {{session("ok")}}
        </div>
    @endif
</x-app-layout>

resources/views/movies/edit.blade.php
<x-app-layout>
    <x-slot name="title">
        Edit movie
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <form method="POST" action="{{route('movie.update', $movie->id)}}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{method_field("PUT")}}

        <p>
            <label class="text-gray-100" for="title">{{__("Title")}}</label>
            <input type="text" name="title" id="title" value="{{$movie->title}}" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="year">{{__("Year")}}</label>
            <input type="text" name="year" id="year" value="{{$movie->year}}" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="length">{{__("Length")}}</label>
            <input type="number" name="length" id="length" value="{{$movie->length}}" max="500" min="20" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="director_id">Director</label>
            <select name="director_id" id="director_id" required
                    class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                @foreach($artists as $artist)
                    <option value="{{$artist->id}}"{{$artist->id == $movie->director_id ? 'selected="selected"' : ''}}>
                        {{$artist->name}}
                        {{$artist->firstname}}
                    </option>
                @endforeach
            </select>
        </p>
        <p>
            <label class="text-gray-100" for="country_id">Country</label>
            <select name="country_id" id="country_id" required
                    class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                @foreach($countries as $country)
                    <option value="{{$country->id}}"{{$country->id == $movie->country_id ? 'selected="selected"' : ''}}>
                        {{$country->name}}
                    </option>
                @endforeach
            </select>
        </p>
        <p>
            <label for="poster" class="form-label inline-block mb-2 text-gray-100">Select a movie poster</label>

            <input type="file" id="poster" name="poster"
                   class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none">

            <img src="{{asset('storage/uploads/posters/'.$movie->poster)}}" alt="{{$movie->title}}" width="100px"
                 height="150px">
        </p>

        <button type="submit"
                class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Update
        </button>
    </form>

    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    @if (session("ok"))
        <div>
            {{session("ok")}}
        </div>
    @endif
</x-app-layout>

resources/views/movies/index.blade.php
<x-app-layout>
    <x-slot name="title">
        Movies
    </x-slot>
    <x-slot name="link">
        <a class="bg-blue-900 hover:bg-blue-800 text-gray-200 font-bold py-2 px-4 rounded inline-flex items-center"
           href="{{ route('movie.create') }}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                 stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                 class="feather feather-plus-circle w-5 h-5 mr-2 ">
                <circle cx="12" cy="12" r="10"/>
                <line x1="12" y1="8" x2="12" y2="16"/>
                <line x1="8" y1="12" x2="16" y2="12"/>
            </svg>
            <span> {{__("Create")}}</span>
        </a>
    </x-slot>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">{{__("Poster")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Title")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Year")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Director")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Country")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Length")}}</th>
                @auth()
                    <th scope="col" class="px-6 py-3 text-right">{{__("Actions")}}</th>
                @endauth
            </tr>
            </thead>
            <tbody>
            @foreach($movies as $movie)
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <td class="px-6 py-4"><img src="{{asset('storage/uploads/posters/'.$movie->poster)}}"
                                               alt="{{$movie->title}}" width="100px" height="150px"></td>
                    <td class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">{{$movie->title}}</td>
                    <td class="px-6 py-4">{{$movie->year}}</td>
                    <td class="px-6 py-4">{{$movie->director->firstname}} {{$movie->director->name}}</td>
                    <td class="px-6 py-4">{{$movie->country->name}}</td>
                    <td class="px-6 py-4">{{$movie->length}} min</td>

                    <x-buttons>
                        <x-slot name="specialLink">
                            <a
                                class="font-medium text-blue-100 hover:underline mr-2 whitespace-nowrap"
                                href="{{ route('movie.actors', $movie->id)}}
                                    ">{{__("See actors")}}</a>
                        </x-slot>

                        <x-slot name="editLink">{{route('movie.edit', $movie->id)}}</x-slot>
                        <x-slot name="deleteLink">{{route('movie.destroy', $movie->id)}}</x-slot>
                    </x-buttons>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    @include("components.script")


</x-app-layout>