routes/web.php
<?php

use App\Http\Controllers\ArtistController;
use App\Http\Controllers\CinemaController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\SessionController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", [CinemaController::class, 'index'])->name('home');

Route::get('dashboard', function () {
    return view('dashboard' . "UserController@profile");
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::get("profile", "UserController@profile")->middleware("auth");


Route::prefix('movie')->group(function () {
    //Route::get("/", ['as' => 'movie', 'uses' => 'MovieController@movie']);
    Route::get('{movie}/actors', [MovieController::class, 'actors'])->name('movie.actors');
    Route::post('{movie}/actors', [MovieController::class, 'attach'])->name('movie.attach');
    Route::get('{movie}/actors/{actor}', [MovieController::class, 'detach'])->name('movie.detach');
});


Route::prefix('artist')->group(function () {
    Route::get('{artist}/filmography', [ArtistController::class, 'hasPlayed'])->name('artist.filmography');
    //    Route::get('{artist}/directed', [ArtistController::class, 'hasDirected'])->name('artist.filmography');
});


Route::resource("artist", ArtistController::class);
Route::resource("country", CountryController::class);
Route::resource("movie", MovieController::class);
Route::resource("cinema", CinemaController::class);
Route::resource("room", RoomController::class);
Route::resource("session", SessionController::class);

app/Models/Artist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Artist extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'firstname', 'birthdate', 'country_id', 'image', "user_id"
    ];


    public function country(): BelongsTo
    {
        return $this->belongsTo(Country::class);
    }

    public function hasDirected(): HasMany
    {
        return $this->hasMany(Movie::class, "director_id");
    }

    public function hasPlayed(): BelongsToMany
    {
        return $this->belongsToMany(Movie::class)->withPivot("role");
    }
}

app/Http/Controllers/ArtistController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ArtistRequest;
use App\Models\Artist;
use App\Models\Country;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;

//use App\Http\Controllers\Auth;


class ArtistController extends Controller

{
    public function __construct()
    {
        $this->middleware('ajax')->only('destroy');
        $this->middleware('auth')->only('create');
        $this->middleware('auth')->only('edit');


    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {

        return view('artists.index', ['artists' => Artist::orderBy('firstname', 'ASC')->get()]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @param Artist $artist
     * @return Application|Factory|View
     */
    public function create(Artist $artist): View|Factory|Application
    {
        return view("artists.create", ["artist" => $artist, "countries" => Country::orderBy('name', 'ASC')->get()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArtistRequest $request
     * @return RedirectResponse
     * @throws Exception
     */
    public function store(ArtistRequest $request): RedirectResponse
    {
        $data = $request->all();
        $data["user_id"] = Auth::user()->id;
        $data["image"] = $request->input('name') . "_" . bin2hex(random_bytes(5)) . ".jpg";

        Artist::create($data);

        $image = $request->file("image");
        Image::make($image)->fit(500, 500)
            ->save(storage_path("app/public/uploads/profiles/" . $data["image"]));

        return redirect()->route("artist.index")
            ->with("ok", __("Artist has been saved"));
    }

    /**
     * Display the specified resource.
     *
     * @return void
     */
    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Artist $artist
     * @return Application|Factory|View
     */
    public function edit(Artist $artist): View|Factory|Application
    {
        return view("artists.edit", ["artist" => $artist, "countries" => Country::orderBy('name', 'ASC')->get()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ArtistRequest $request
     * @param Artist $artist
     * @return RedirectResponse
     * @throws Exception
     */
    public function update(ArtistRequest $request, Artist $artist): RedirectResponse
    {
        if ($artist->user_id == Auth::user()->id) {
            $data = $request->all();
            if (!isset($data["image"])) {
                $data["image"] = $artist->image;
            } else {
                $data["image"] = $request->input('name') . "_" . bin2hex(random_bytes(5)) . ".jpg";
                $image = $request->file("image");
                Image::make($image)->fit(500, 500)
                    ->save(storage_path("app/public/uploads/profiles/" . $data["image"]));
            }
            $artist->update($data);

            return redirect()->route("artist.index")
                ->with("ok", __("Artist has been updated"));
        }

        abort(403, 'Unauthorized action.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Artist $artist
     * @return JsonResponse
     */
    public function destroy(Artist $artist): JsonResponse
    {
        if ($artist->user_id == Auth::user()->id) {
            $artist->delete();
            return response()->json();
        }

        abort(403, 'Unauthorized action.');

    }

    public function hasPlayed($id): Factory|View|Application
    {
        return view('artists.filmography', ["artist" => Artist::findOrFail($id), "movies" => Artist::find($id)->hasPlayed()->get()]);
        //return view('movies.actors', ["actors" => Movie::where("id", $id)->first()->actors()->get(), 'movie' => Movie::findOrFail($id), 'artists' => Artist::orderBy('name', 'ASC')->get()
    }

//    public function hasDirected($id): Factory|View|Application
//    {
//        return view('artists.filmography', ["artist" => Artist::findOrFail($id), "movies" => Artist::find($id)->hasDirected()->get()]);
//        //return view('movies.actors', ["actors" => Movie::where("id", $id)->first()->actors()->get(), 'movie' => Movie::findOrFail($id), 'artists' => Artist::orderBy('name', 'ASC')->get()
//    }


}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/artists/create.blade.php
<x-app-layout>
    <x-slot name="title">
        Test
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <form method="POST" action="{{route('artist.store')}}" enctype="multipart/form-data">
        {{ csrf_field() }}

        <p>
            <label class="text-gray-100" for="name">Name</label>
            <input type="text" name="name" id="name" value="" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="firstname">Firstname</label>
            <input type="text" name="firstname" id="firstname" value="" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="birthdate">Birthdate</label>
            <input type="number" name="birthdate" id="birthdate" value="" max="2010" min="1910"
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="country_id">Country</label>
            <select name="country_id" id="country_id" required
                    class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                @foreach($countries as $country)
                    <option
                        value="{{$country->id}}"{{$country->id == $artist->country_id ? 'selected="selected"' : ''}}>
                        {{$country->name}}
                    </option>
                @endforeach
            </select>
        </p>
        <p>
            <label for="image" class="form-label inline-block mb-2 text-gray-100">Select a profile image</label>
            <input type="file" id="image" name="image"
                   class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none">
        </p>
        <button type="submit"
                class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Create
        </button>
    </form>

    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if (session("ok"))
        <div>
            {{session("ok")}}
        </div>
    @endif
</x-app-layout>

resources/views/artists/edit.blade.php
<x-app-layout>
    <x-slot name="title">
        Edit Artist
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <form method="POST" action="{{route('artist.update', $artist->id)}}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{method_field("PUT")}}

        <p>
            <label class="text-gray-100" for="name">{{__("Name")}}</label>
            <input type="text" name="name" id="name" value="{{$artist->name}}" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="firstname">{{__("Firstname")}}</label>
            <input type="text" name="firstname" id="firstname" value="{{$artist->firstname}}" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="birthdate">{{__("Birthdate")}}</label>
            <input type="number" name="birthdate" id="birthdate" value="{{$artist->birthdate}}"
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="country_id">Country</label>

            <select name="country_id" id="country_id" required
                    class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                @foreach($countries as $country)
                    <option
                        value="{{$country->id}}"{{$country->id == $artist->country_id ? 'selected="selected"' : ''}}>
                        {{$country->name}}
                    </option>
                @endforeach
            </select>
        </p>
        <p>
            <label for="image" class="form-label inline-block mb-2 text-gray-100">Select a profile image</label>
            <input type="file" id="image" name="image"
                   class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none">
            <img src="{{asset('storage/uploads/profiles/'.$artist->image)}}" alt="{{$artist->name}}" width="100px"
                 height="100px">

        </p>

        <button type="submit"
                class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Update
        </button>
    </form>

    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    @if (session("ok"))
        <div>
            {{session("ok")}}
        </div>
    @endif
</x-app-layout>

resources/views/artists/filmography.blade.php
<x-app-layout>
    <x-slot name="title">
        Filmography
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <div class="flex flex-wrap justify-center">
        <div class=" text-center">
            {{--            <h1 class="text-5xl font-normal leading-normal mt-0 mb-2 text-stone-100">Movies--}}
            {{--                where {{$artist->firstname }} {{$artist->name }} as played--}}
            {{--            </h1>--}}
            <img src="{{asset('storage/uploads/profiles/'.$artist->image)}}"
                 alt="{{$artist->firstname }} {{$artist->name }}" width="200px" height="200px"
                 class="mb-5 rounded-full">
            <h2 class="mb-5 text-xl">{{$artist->firstname }} {{$artist->name }}</h2>
        </div>
    </div>

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">


        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">{{__("Posters")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Title")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Role")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Country of production")}}</th>

                {{--                <th scope="col" class="px-6 py-3">{{__("Actions")}}</th>--}}

            </tr>
            </thead>
            <tbody>
            @foreach($movies as $movie)

                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <td class="px-6 py-4"><img class=""
                                               src="{{asset('storage/uploads/posters/'.$movie->poster)}}"
                                               alt="{{$movie->title}}" width="100px"
                                               height="150px"></td>
                    <td class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">{{$movie->title}}</td>
                    <td class="px-6 py-4">{{$movie->pivot->role}}</td>
                    <td class="px-6 py-4">{{$movie->country->name}}</td>

                {{--                    <td class="px-6 py-4 text-right">--}}
                {{--                        <a href="{{route('movie.detach', ["movie"=>$movie->id, "actor"=>$actor->id])}}"--}}
                {{--                           class="font-medium text-blue-600 dark:text-blue-500 hover:underline">{{__('Detach')}}</a>--}}
                {{--                </tr>--}}
            @endforeach
            </tbody>
        </table>


    </div>

</x-app-layout>

resources/views/artists/index.blade.php
<x-app-layout>
    <x-slot name="title">
        Artists
    </x-slot>
    <x-slot name="link">
        <a class="bg-blue-900 hover:bg-blue-800 text-gray-200 font-bold py-2 px-4 rounded inline-flex items-center"
           href="{{ route('artist.create') }}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                 stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                 class="feather feather-plus-circle w-5 h-5 mr-2 ">
                <circle cx="12" cy="12" r="10"/>
                <line x1="12" y1="8" x2="12" y2="16"/>
                <line x1="8" y1="12" x2="16" y2="12"/>
            </svg>
            <span> {{__("Create")}}</span>
        </a>
    </x-slot>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">{{__("Profile")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Name")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Country")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Birthdate")}}</th>
                @auth()
                    <th scope="col" class="px-6 py-3 text-right">{{__("Actions")}}</th>
                @endauth

            </tr>
            </thead>
            <tbody>
            @foreach($artists as $artist)
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">

                    <td class="px-6 py-4">
                        @if($artist->image)
                            <img src="{{asset('storage/uploads/profiles/'.$artist->image)}}"
                                 alt="{{$artist->firstname." ".$artist->name }}" width="100px"
                                 height="100px" class="rounded-full">
                        @else
                            <img src="{{asset('storage/uploads/profiles/placeholder.jpg')}}"
                                 alt="placeholder" width="100px"
                                 height="100px" class="rounded-full">
                        @endif

                    </td>
                    <td class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">{{$artist->firstname}} {{$artist->name}}</td>
                    <td class="px-6 py-4">{{$artist->country->name}}</td>
                    <td class="px-6 py-4">{{$artist->birthdate}}</td>

                    <x-buttons>
                        <x-slot name="specialLink">
                            <a href="{{route('artist.filmography', $artist->id)}}"
                               class="font-medium text-blue-100 hover:underline mr-2">{{__('Filmography')}}</a>
                        </x-slot>

                        <x-slot name="editLink">{{route('artist.edit', $artist->id)}}</x-slot>
                        <x-slot name="deleteLink">{{route('artist.destroy', $artist->id)}}</x-slot>
                    </x-buttons>

                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    @include("components.script")
</x-app-layout>