routes/web.php
<?php

use App\Http\Controllers\ArtistController;
use App\Http\Controllers\CinemaController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\SessionController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", [CinemaController::class, 'index'])->name('home');

Route::get('dashboard', function () {
    return view('dashboard' . "UserController@profile");
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::get("profile", "UserController@profile")->middleware("auth");


Route::prefix('movie')->group(function () {
    //Route::get("/", ['as' => 'movie', 'uses' => 'MovieController@movie']);
    Route::get('{movie}/actors', [MovieController::class, 'actors'])->name('movie.actors');
    Route::post('{movie}/actors', [MovieController::class, 'attach'])->name('movie.attach');
    Route::get('{movie}/actors/{actor}', [MovieController::class, 'detach'])->name('movie.detach');
});


Route::prefix('artist')->group(function () {
    Route::get('{artist}/filmography', [ArtistController::class, 'hasPlayed'])->name('artist.filmography');
    //    Route::get('{artist}/directed', [ArtistController::class, 'hasDirected'])->name('artist.filmography');
});


Route::resource("artist", ArtistController::class);
Route::resource("country", CountryController::class);
Route::resource("movie", MovieController::class);
Route::resource("cinema", CinemaController::class);
Route::resource("room", RoomController::class);
Route::resource("session", SessionController::class);

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'size', 'cinema_id', "user_id"
    ];

    public function cinema()
    {
        return $this->belongsTo(Cinema::class);
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RoomRequest;
use App\Models\Cinema;
use App\Models\Room;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('ajax')->only('destroy');
        $this->middleware('auth')->only('create');
        $this->middleware('auth')->only('edit');

    }

    public function index(): Factory|View|Application
    {

        return view('rooms.index', ['rooms' => Room::orderBy('name', 'ASC')->get(), "cinemas" => Cinema::all()]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Room $room
     * @return Application|Factory|View
     */
    public function create(Room $room): View|Factory|Application
    {

        return view("rooms.create", ["rooms" => $room, 'cinemas' => Cinema::orderBy('name', 'ASC')->get()]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RoomRequest $request
     * @return RedirectResponse
     */
    public function store(RoomRequest $request): RedirectResponse
    {
        $data = $request->all();
        $data["user_id"] = Auth::user()->id;
        Room::create($data);
        return redirect()->route("room.index")
            ->with("ok", __("Room has been saved"));
    }

    /**
     * Display the specified resource.
     *
     * @param Room $room
     * @return void
     */
    public function show(Room $room)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Room $room
     * @return Application|Factory|View
     */
    public function edit(Room $room): View|Factory|Application
    {
        return view("rooms.edit", ["room" => $room, 'cinemas' => Cinema::orderBy('name', 'ASC')->get()]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param RoomRequest $request
     * @param Room $room
     * @return RedirectResponse
     */
    public function update(RoomRequest $request, Room $room): RedirectResponse
    {
        if ($room->user_id == Auth::user()->id) {
            $data = $request->all();
            $room->update($data);
            return redirect()->route("room.index")
                ->with("ok", __("Movie has been updated"));
        }

        abort(403, 'Unauthorized action.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Room $room
     * @return RedirectResponse
     */
    public function destroy(Room $room): RedirectResponse
    {
        if ($room->user_id == Auth::user()->id) {

            $room->delete();
            return redirect()->back();
        }

        abort(403, 'Unauthorized action.');

    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/rooms/create.blade.php
<x-app-layout>
    <x-slot name="title">
        Create Room
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <form method="POST" action="{{route('room.store')}}" enctype="multipart/form-data">
        {{ csrf_field() }}

        <p>
            <label class="text-gray-100" for="name">Room</label>
            <input type="text" name="name" id="name" value="" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="size">Size</label>
            <input type="number" name="size" id="size" value="" max="1000" min="50" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="cinema_id">Cinema</label>
            <select name="cinema_id" id="cinema_id" required
                    class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                @foreach($cinemas as $cinema)
                    <option value="{{$cinema->id}}"{{$cinema->id == $cinema->cinema_id ? 'selected="selected"' : ''}}>
                        {{$cinema->name}}
                    </option>
                @endforeach
            </select>
        </p>
        <button type="submit"
                class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Create
        </button>
    </form>

    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    @if (session("ok"))
        <div>
            {{session("ok")}}
        </div>
    @endif
</x-app-layout>

resources/views/rooms/edit.blade.php
<x-app-layout>
    <x-slot name="title">
        Edit room
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <form method="POST" action="{{route('room.update', $room->id)}}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{method_field("PUT")}}

        <p>
            <label class="text-gray-100" for="name">{{__("Name")}}</label>
            <input type="text" name="name" id="name" value="{{$room->name}}" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="size">{{__("size")}}</label>
            <input type="text" name="size" id="size" value="{{$room->size}}" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="cinema_id">cinema</label>
            <select name="cinema_id" id="cinema_id" required
                    class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                @foreach($cinemas as $cinema)
                    <option value="{{$cinema->id}}"{{$cinema->id == $room->cinema_id ? 'selected="selected"' : ''}}>
                        {{$cinema->name}}
                    </option>
                @endforeach
            </select>
        </p>

        <button type="submit"
                class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Update
        </button>
    </form>

    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    @if (session("ok"))
        <div>
            {{session("ok")}}
        </div>
    @endif
</x-app-layout>

resources/views/rooms/index.blade.php
<x-app-layout>
    <x-slot name="title">
        Rooms
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <x-slot name="link">
        <a class="bg-blue-900 hover:bg-blue-800 text-gray-200 font-bold py-2 px-4 rounded inline-flex items-center"
           href="{{ route('room.create') }}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                 stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                 class="feather feather-plus-circle w-5 h-5 mr-2 ">
                <circle cx="12" cy="12" r="10"/>
                <line x1="12" y1="8" x2="12" y2="16"/>
                <line x1="8" y1="12" x2="16" y2="12"/>
            </svg>
            <span> {{__("Create")}}</span>
        </a>
    </x-slot>

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">

        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">{{__("Name")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Size")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Cinema")}}</th>
                @auth()
                    <th scope="col" class="px-6 py-3 text-right">{{__("Actions")}}</th>
                @endauth

            </tr>
            </thead>
            <tbody>
            @foreach($rooms as $room)
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <td class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">{{$room->name}}</td>
                    <td class="px-6 py-4">{{$room->size}} seats</td>
                    <td class="px-6 py-4">{{$room->cinema->name}}</td>
                    <x-buttons>
                        <x-slot name="specialLink"></x-slot>
                        <x-slot name="editLink">{{route('room.edit', $room->id)}}</x-slot>
                        <x-slot name="deleteLink">{{route('room.destroy', $room->id)}}</x-slot>
                    </x-buttons>
            @endforeach
            </tbody>
        </table>
    </div>
    @include("components.script")

</x-app-layout>