routes/web.php
<?php

use App\Http\Controllers\ArtistController;
use App\Http\Controllers\CinemaController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\SessionController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", [CinemaController::class, 'index'])->name('home');

Route::get('dashboard', function () {
    return view('dashboard' . "UserController@profile");
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::get("profile", "UserController@profile")->middleware("auth");


Route::prefix('movie')->group(function () {
    //Route::get("/", ['as' => 'movie', 'uses' => 'MovieController@movie']);
    Route::get('{movie}/actors', [MovieController::class, 'actors'])->name('movie.actors');
    Route::post('{movie}/actors', [MovieController::class, 'attach'])->name('movie.attach');
    Route::get('{movie}/actors/{actor}', [MovieController::class, 'detach'])->name('movie.detach');
});


Route::prefix('artist')->group(function () {
    Route::get('{artist}/filmography', [ArtistController::class, 'hasPlayed'])->name('artist.filmography');
    //    Route::get('{artist}/directed', [ArtistController::class, 'hasDirected'])->name('artist.filmography');
});


Route::resource("artist", ArtistController::class);
Route::resource("country", CountryController::class);
Route::resource("movie", MovieController::class);
Route::resource("cinema", CinemaController::class);
Route::resource("room", RoomController::class);
Route::resource("session", SessionController::class);

app/Models/Cinema.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cinema extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', "address", "country_id", "user_id"
    ];


    public function country()
    {
        return $this->belongsTo(Country::class);
    }
}

app/Http/Controllers/CinemaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CinemaRequest;
use App\Models\Cinema;
use App\Models\Country;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;

class CinemaController extends Controller
{
    public function __construct()
    {
        $this->middleware('ajax')->only('destroy');
        $this->middleware('auth')->only('create');
        $this->middleware('auth')->only('edit');

    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {
        return view('cinemas.index', ['cinemas' => Cinema::all(), "countries" => Country::orderBy('name', 'ASC')->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Cinema $cinema
     * @return Application|Factory|View
     */
    public function create(Cinema $cinema): View|Factory|Application
    {
        return view("cinemas.create", ["cinema" => $cinema, "countries" => Country::orderBy('name', 'ASC')->get()]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CinemaRequest $request
     * @return RedirectResponse
     */
    public function store(CinemaRequest $request): RedirectResponse
    {
        $data = $request->all();
        $data["user_id"] = Auth::user()->id;

        Cinema::create($data);
        return redirect()->route("cinema.index")
            ->with("ok", __("Cinema has been saved"));
    }

    /**
     * Display the specified resource.
     *
     */
    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Cinema $cinema
     * @return Application|Factory|View
     */
    public function edit(Cinema $cinema): View|Factory|Application
    {
        return view("cinemas.edit", ["cinema" => $cinema, "countries" => Country::orderBy('name', 'ASC')->get()]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param CinemaRequest $request
     * @param Cinema $cinema
     * @return RedirectResponse
     */
    public function update(CinemaRequest $request, Cinema $cinema): RedirectResponse
    {
        if ($cinema->user_id == Auth::user()->id) {

            $data = $request->all();
            $cinema->update($data);

            return redirect()->route("cinema.index")
                ->with("ok", __("Cinema has been updated"));
        }

        abort(403, 'Unauthorized action.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Cinema $cinema
     * @return RedirectResponse
     */
    public function destroy(Cinema $cinema): RedirectResponse
    {
        if ($cinema->user_id == Auth::user()->id) {
            $cinema->delete();
            return redirect()->back();
        }

        abort(403, 'Unauthorized action.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/cinemas/create.blade.php
<x-app-layout>
    <x-slot name="title">
        Create Cinemas
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <form method="POST" action="{{route('cinema.store')}}" enctype="multipart/form-data">
        {{ csrf_field() }}

        <p>
            <label class="text-gray-100" for="name">Name</label>
            <input type="text" name="name" id="name" value="" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="address">Adress</label>
            <input type="text" name="address" id="address" value="" max="2022" min="1900" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="country_id">Country</label>
            <select name="country_id" id="country_id" required
                    class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                @foreach($countries as $country)
                    <option
                        value="{{$country->id}}"{{$country->id == $cinema->country_id ? 'selected="selected"' : ''}}>
                        {{$country->name}}
                    </option>
                @endforeach
            </select>
        </p>
        <button type="submit"
                class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Create
        </button>
    </form>

    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    @if (session("ok"))
        <div>
            {{session("ok")}}
        </div>
    @endif
</x-app-layout>

resources/views/cinemas/edit.blade.php
<x-app-layout>
    <x-slot name="title">
        Edit cinema
    </x-slot>
    <x-slot name="link">

    </x-slot>
    <form method="POST" action="{{route('cinema.update', $cinema->id)}}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{method_field("PUT")}}

        <p>
            <label class="text-gray-100" for="name">{{__("Name")}}</label>
            <input type="text" name="name" id="name" value="{{$cinema->name}}" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="address">{{__("Address")}}</label>
            <input type="text" name="address" id="address" value="{{$cinema->address}}" required
                   class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
        </p>
        <p>
            <label class="text-gray-100" for="country_id">Country</label>
            <select name="country_id" id="country_id" required
                    class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm">
                @foreach($countries as $country)
                    <option
                        value="{{$country->id}}"{{$country->id == $cinema->country_id ? 'selected="selected"' : ''}}>
                        {{$country->name}}
                    </option>
                @endforeach
            </select>
        </p>

        <button type="submit"
                class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Update
        </button>
    </form>

    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    @if (session("ok"))
        <div>
            {{session("ok")}}
        </div>
    @endif
</x-app-layout>

resources/views/cinemas/index.blade.php
<x-app-layout>
    <x-slot name="title">
        {{ __('Cinema') }}

    </x-slot>
    <x-slot name="link">
        <a class="bg-blue-900 hover:bg-blue-800 text-gray-200 font-bold py-2 px-4 rounded inline-flex items-center"
           href="{{ route('cinema.create') }}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                 stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                 class="feather feather-plus-circle w-5 h-5 mr-2 ">
                <circle cx="12" cy="12" r="10"/>
                <line x1="12" y1="8" x2="12" y2="16"/>
                <line x1="8" y1="12" x2="16" y2="12"/>
            </svg>
            <span> {{__("Create")}}</span>
        </a>
    </x-slot>

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">

        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">{{__("Name")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Address")}}</th>
                <th scope="col" class="px-6 py-3">{{__("Country")}}</th>
                @auth()
                    <th scope="col" class="px-6 py-3 text-right">{{__("Actions")}}</th>
                @endauth

            </tr>
            </thead>
            <tbody>

            @foreach($cinemas as $cinema)
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <td class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">{{$cinema->name}}</td>
                    <td class="px-6 py-4">{{$cinema->address}}</td>
                    <td class="px-6 py-4">{{$cinema->country->name}}</td>
                    <x-buttons>
                        <x-slot name="specialLink"></x-slot>
                        <x-slot name="editLink">{{route('cinema.edit', $cinema->id)}}</x-slot>
                        <x-slot name="deleteLink">{{route('cinema.destroy', $cinema->id)}}</x-slot>
                    </x-buttons>

                </tr>

            @endforeach


            </tbody>
        </table>
    </div>
    @include("components.script")

</x-app-layout>